name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran liblapack-dev liblapacke-dev

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build
